name: Build Kernel

on:
  workflow_dispatch:

    inputs:
      KERNEL_SOURCE:
        description: 'Kernel Source'
        required: true
        default: 'Rohail33/Realking_kernel_sm8250'
      KERNEL_SOURCE_BRANCH:
        description: 'Branch'
        required: true
        default: 'opkona'
      KERNEL_DEFCONFIG:
        description: 'Defconfig'
        required: true
        default: 'vendor/opkona_defconfig'
      TARGET_ARCH:
        description: 'Target ARCH'
        required: true
        default: 'arm64'
      KERNEL_FILE:
        description: 'Your kernel out image name'
        required: true
        default: 'Image.gz'
      CLANG_URL:
        description: 'Clang URL'
        required: true
        default: 'https://github.com/ZyCromerZ/Clang/releases/download/17.0.0-20230217-release/Clang-17.0.0-20230217.tar.gz'
      BUILD_EXTRA_COMMAND:
        description: 'Extra build commands(e.g. LLVM=1 LLVM_IAS=1)'
        required: false
        default: 'NM=llvm-nm OBJDUMP=llvm-objdump STRIP=llvm-strip'
      USE_KPROBES:
        description: 'Use Kprobes'
        required: false
        default: 'true'
        type: boolean
      USE_KERNELSU:
        description: 'Use KernelSU'
        required: true
        default: 'true'
        type: boolean
      SSH:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
        type: boolean

jobs:
     name:

          runs-on: ubuntu-latest

          steps:
            - uses: actions/checkout@v4
            - name: configure
              run: ./build_kernel.sh
